import {
  BuildingOfficeIcon,
  CheckBadgeIcon,
  CheckIcon,
  EyeIcon,
  EyeSlashIcon,
  FireIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  FunnelIcon,
  SparklesIcon,
  ShieldCheckIcon,
  CubeIcon,
  ChartBarIcon,
  BeakerIcon,
  TruckIcon,
  ChartPieIcon,
  WrenchIcon,
  HeartIcon as HeartIconSolid,
  StarIcon as StarIconSolid,
  ChevronDownIcon,
  AdjustmentsVerticalIcon,
} from "@heroicons/react/20/solid";

import {
  XMarkIcon,
  HeartIcon,
  StarIcon,
  Bars3Icon,
  UserCircleIcon,
  MapPinIcon,
  PhoneIcon,
  EnvelopeIcon,
  GlobeAltIcon,
} from "@heroicons/react/24/outline";

import { FaGoogle } from "react-icons/fa";

export {
  BuildingOfficeIcon,
  CheckBadgeIcon,
  CheckIcon,
  EyeIcon,
  EyeSlashIcon,
  FireIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  FunnelIcon,
  MapPinIcon,
  SparklesIcon,
  ShieldCheckIcon,
  CubeIcon,
  ChartBarIcon,
  BeakerIcon,
  TruckIcon,
  ChartPieIcon,
  WrenchIcon,
  StarIcon,
  HeartIcon,
  ChevronDownIcon,
  XMarkIcon,
  AdjustmentsVerticalIcon,
  PhoneIcon,
  EnvelopeIcon,
  GlobeAltIcon,
  HeartIconSolid,
  StarIconSolid,
  Bars3Icon,
  UserCircleIcon,
  FaGoogle,
};
